export enum Role {
  REQUESTER = 'Solicitante (Usuário 1)',
  MANAGER = 'Gerente (Usuário 2)',
  ANALYST = 'Analista (Usuário 3)',
  ADMIN = 'Administrador',
}

export enum ProcessStatus {
  PENDING = 'Pendente',
  DISTRIBUTED = 'Distribuído',
  COMPLETED = 'Concluído',
}

// Novos status dinâmicos criados pelo Admin
export interface StatusOption {
  id: string;
  label: string;
  color: string; // tailwind color class prefix (e.g., 'bg-red-100 text-red-700')
}

export interface ProductGroup {
  id: string;
  name: string;
}

export interface User {
  id: string;
  name: string;
  role: Role;
  active: boolean;
  avatarColor?: string;
}

export interface ProductDatabaseItem {
  familia: string;
  idGMS: string;
  descricao: string;
  consolidadoDT: string;
  estoque: number;
}

export interface RequestItem {
  gmsCode?: string; // {{ item.codigo_gms }}
  lote: string;     // {{ item.lote }}
  quantidade: number; // {{ item.quantidade_solicitada }}
  consolidadoDT: string; // {{ item.consumo_anual }}
  estoqueAtual: number; // {{ item.estoque_atual }}
  descricao: string; // {{ item.item_descricao }}
  valorUnitario?: number; // {{ item.valor_unitario }} - Preenchido pelo Analista
}

export interface ProcessData {
  id: string;
  requesterName: string;
  ataPregao: string; // {{ pe_numero }} ou {{ NUMERO_PE }}
  
  items: RequestItem[];

  createdAt: string;
  
  // Manager fields
  assignedTo?: string; // Analyst Name
  distributedAt?: string;

  // Analyst fields
  memoNumber?: string; // {{ numero_memorando }}
  protocolNumber?: string; // {{ NUMERO_PROTOCOLO }}
  
  numeroAta?: string; // {{ NUMERO_ATA }}
  validadeAta?: string; // {{ VALIDADE_ATA }}
  
  productGroupId?: string; // ID do grupo de produtos
  totalValue?: number; // {{ SOMA DO VALOR TOTAL DE CADA ITEM }}
  
  aiSubject?: string; // {{ assunto_memo }}
  aiMotivation?: string; // {{ texto_ia_motivacao }}
  
  finalDocumentText?: string; // Generated by AI (Legacy full text)
  completedAt?: string;
  
  // Controle de fluxo
  status: ProcessStatus; // Status sistêmico (Hardcoded logic)
  customStatusId?: string; // Status informativo (Dynamic logic from Admin)
}

export interface KPIData {
  name: string;
  value: number;
}

export interface DocumentTemplate {
  id: string;
  name: string;
  type: 'docx' | 'xlsx';
  fileName: string;
  lastUpdated: string;
}